// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzEITsuhZqXONrULRgkdxTtzpmhKIAdK8',
    appId: '1:305816586207:web:52f6f61ef22ad76d90e66a',
    messagingSenderId: '305816586207',
    projectId: 'first-snow-1347c',
    authDomain: 'first-snow-1347c.firebaseapp.com',
    storageBucket: 'first-snow-1347c.appspot.com',
    measurementId: 'G-BBHEG4M2G6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwc7WcxiUa79pLQGjesxy-qCNtZ-xxyU8',
    appId: '1:305816586207:android:6c6c089b04a8504990e66a',
    messagingSenderId: '305816586207',
    projectId: 'first-snow-1347c',
    storageBucket: 'first-snow-1347c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7zT-DK3zY4915ELeRxb0b80QlwYTrfzc',
    appId: '1:305816586207:ios:6b76fe25aee06e8490e66a',
    messagingSenderId: '305816586207',
    projectId: 'first-snow-1347c',
    storageBucket: 'first-snow-1347c.appspot.com',
    iosBundleId: 'com.example.firstSnow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7zT-DK3zY4915ELeRxb0b80QlwYTrfzc',
    appId: '1:305816586207:ios:6b76fe25aee06e8490e66a',
    messagingSenderId: '305816586207',
    projectId: 'first-snow-1347c',
    storageBucket: 'first-snow-1347c.appspot.com',
    iosBundleId: 'com.example.firstSnow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzEITsuhZqXONrULRgkdxTtzpmhKIAdK8',
    appId: '1:305816586207:web:9cfcd5cb8605233790e66a',
    messagingSenderId: '305816586207',
    projectId: 'first-snow-1347c',
    authDomain: 'first-snow-1347c.firebaseapp.com',
    storageBucket: 'first-snow-1347c.appspot.com',
    measurementId: 'G-76DN3KF9M5',
  );
}
